import { Listing, ListingType, User, Gender } from './types';

export const CURRENT_USER: User = {
  userId: 1,
  firstName: "Jane",
  lastName: "Doe",
  email: "jane.doe@example.com",
  isActive: true,
  gender: Gender.Female,
  profilePicture: "https://picsum.photos/seed/user1/200/200",
  bookmarkedListingIds: [102],
  createdListingIds: [101],
};

export const MOCK_LISTINGS: Listing[] = [
  {
    listingId: 101,
    listingType: ListingType.Apartment,
    address: "123 University Ave",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45219",
    country: "USA",
    rent: 850,
    startAvailability: "2024-08-01",
    endAvailability: "2024-12-15",
    bedrooms: 2,
    bathrooms: 1,
    description: "Cozy apartment right next to campus. Great for engineering students.",
    waterIncludedInRent: true,
    gasIncludedInRent: false,
    internetIncludedInRent: true,
    trashIncludedInRent: true,
    electricIncludedInRent: false,
    averageUtilitiesCost: 50,
    furnished: true,
    animalsAllowed: 4,
    washerDryer: 2,
    parking: 0,
    distanceFromCampus: 0.2,
    photos: ["https://picsum.photos/seed/101/800/600", "https://picsum.photos/seed/101b/800/600"],
    roommateNumber: 1,
    contact: "555-0101",
    contactName: "Jane Doe",
    ownerId: 1,
    bookmarkedByIds: []
  },
  {
    listingId: 102,
    listingType: ListingType.House,
    address: "456 Clifton Heights",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45220",
    country: "USA",
    rent: 1200,
    startAvailability: "2024-08-20",
    endAvailability: "2025-05-01",
    bedrooms: 4,
    bathrooms: 2,
    description: "Spacious house with a large backyard. Perfect for a group of friends.",
    waterIncludedInRent: false,
    gasIncludedInRent: false,
    internetIncludedInRent: false,
    trashIncludedInRent: true,
    electricIncludedInRent: false,
    averageUtilitiesCost: 120,
    furnished: false,
    animalsAllowed: 0,
    washerDryer: 1,
    parking: 1,
    distanceFromCampus: 1.5,
    photos: ["https://picsum.photos/seed/102/800/600", "https://picsum.photos/seed/102b/800/600"],
    roommateNumber: 3,
    contact: "555-0102",
    contactName: "John Smith",
    ownerId: 2,
    bookmarkedByIds: [1]
  },
  {
    listingId: 103,
    listingType: ListingType.Duplex,
    address: "789 McMillan St",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45206",
    country: "USA",
    rent: 950,
    startAvailability: "2024-09-01",
    endAvailability: "2024-12-31",
    bedrooms: 1,
    bathrooms: 1,
    description: "Newly renovated duplex unit. Modern kitchen and bath.",
    waterIncludedInRent: true,
    gasIncludedInRent: true,
    internetIncludedInRent: true,
    trashIncludedInRent: true,
    electricIncludedInRent: true,
    averageUtilitiesCost: 0,
    furnished: true,
    animalsAllowed: 1,
    washerDryer: 1,
    parking: 0,
    distanceFromCampus: 0.8,
    photos: ["https://picsum.photos/seed/103/800/600"],
    roommateNumber: 0,
    contact: "555-0103",
    contactName: "Alice Wonderland",
    ownerId: 3,
    bookmarkedByIds: []
  },
  {
    listingId: 104,
    listingType: ListingType.Apartment,
    address: "321 Short Vine",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45219",
    country: "USA",
    rent: 600,
    startAvailability: "2024-05-01",
    endAvailability: "2024-08-15",
    bedrooms: 3,
    bathrooms: 1,
    description: "Summer sublet available! Walking distance to all the bars and restaurants.",
    waterIncludedInRent: true,
    gasIncludedInRent: false,
    internetIncludedInRent: false,
    trashIncludedInRent: true,
    electricIncludedInRent: false,
    averageUtilitiesCost: 40,
    furnished: true,
    animalsAllowed: 2,
    washerDryer: 2,
    parking: 3,
    distanceFromCampus: 0.1,
    photos: ["https://picsum.photos/seed/104/800/600"],
    roommateNumber: 2,
    contact: "555-0104",
    contactName: "Bob Builder",
    ownerId: 4,
    bookmarkedByIds: []
  },
   {
    listingId: 105,
    listingType: ListingType.House,
    address: "555 Flora St",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45219",
    country: "USA",
    rent: 750,
    startAvailability: "2024-08-01",
    endAvailability: "2025-07-31",
    bedrooms: 5,
    bathrooms: 2,
    description: "Historic house with lots of character. Hardwood floors throughout.",
    waterIncludedInRent: false,
    gasIncludedInRent: false,
    internetIncludedInRent: false,
    trashIncludedInRent: false,
    electricIncludedInRent: false,
    averageUtilitiesCost: 150,
    furnished: false,
    animalsAllowed: 0,
    washerDryer: 1,
    parking: 1,
    distanceFromCampus: 0.5,
    photos: ["https://picsum.photos/seed/105/800/600"],
    roommateNumber: 4,
    contact: "555-0105",
    contactName: "Charlie Brown",
    ownerId: 5,
    bookmarkedByIds: []
  }
];