namespace SubletUC.Objects
{
    public  class SampleData
    {
        public  User SampleUser => new User
        {
            UserId = 1,
            FullName = "Steve Smargleflargle",
            FirstName = "Steve",
            LastName = "SmargleFlargle",
            Email = "SmargleFlargle@example.com",
            IsActive = true,
            CreatedBy = "System",
            UpdatedBy = "System",
            CreatedDate = DateTime.UtcNow.AddMonths(-2),
            UpdatedDate = DateTime.UtcNow,
            Listings = new List<Listing>
            {
                new Listing
                {
                    ListingId = 1,
                    ListingType = ListingType.Apartment,
                    Address = "123 Main St",
                    AddressLine2 = "Apt 2B",
                    City = "Cincinnati",
                    State = "OH",
                    ZipCode = "45219",
                    Country = "USA",
                    Rent = 950.00m,
                    StartAvailability = new DateTime(2025, 1, 1),
                    EndAvailability = new DateTime(2025, 8, 15),
                    SemesterAvailability = null,
                    Bedrooms = 2,
                    Bathrooms = 1,
                    Description = "Spacious 2-bedroom apartment near UC campus with modern kitchen and parking.",
                    WaterIncludedInRent = true,
                    GasIncludedInRent = false,
                    InternetIncludedInRent = true,
                    TrashIncludedInRent = true,
                    ElectricIncludedInRent = false,
                    AverageUtilitiesCost = 75.00m,
                    SharedRoom = false,
                    SharedRoommates = 0,
                    Furnished = true,
                    AnimalsAllowed = 1,
                    WasherDryer = 1,
                    Parking = 1,
                    DistanceFromCampus = 0.5m,
                    Photos = null,
                    PhotoData = null,
                    RoommateNumber = 0,
                    PreferredGender = Gender.Male,
                    ContactMethod = "Email",
                    Contact = "chris.taylor@example.com",
                    ContactName = "Chris Taylor",
                    Deleted = false,
                    OwnerId = 1
                },
                new Listing
                {
                    ListingId = 2,
                    ListingType = ListingType.House,
                    Address = "456 Oak Ave",
                    AddressLine2 = "",
                    City = "Cincinnati",
                    State = "OH",
                    ZipCode = "45220",
                    Country = "USA",
                    Rent = 1200.00m,
                    StartAvailability = null,
                    EndAvailability = null,
                    SemesterAvailability = "Summer 2025",
                    Bedrooms = 3,
                    Bathrooms = 2,
                    Description = "Cozy 3-bedroom house with fenced yard and nearby bus stop.",
                    WaterIncludedInRent = false,
                    GasIncludedInRent = false,
                    InternetIncludedInRent = true,
                    TrashIncludedInRent = true,
                    ElectricIncludedInRent = false,
                    AverageUtilitiesCost = 150.00m,
                    SharedRoom = false,
                    SharedRoommates = 0,
                    Furnished = false,
                    AnimalsAllowed = 2,
                    WasherDryer = 1,
                    Parking = 2,
                    DistanceFromCampus = 1.2m,
                    Photos = null,
                    PhotoData = null,
                    RoommateNumber = 0,
                    PreferredGender = Gender.Female,
                    ContactMethod = "Phone",
                    Contact = "513-555-1234",
                    ContactName = "Chris Taylor",
                    Deleted = false,
                    OwnerId = 1
                },
                new Listing
                {
                    ListingId = 3,
                    ListingType = ListingType.House,
                    Address = "789 Maple Blvd",
                    AddressLine2 = "Room 3",
                    City = "Cincinnati",
                    State = "OH",
                    ZipCode = "45219",
                    Country = "USA",
                    Rent = 600.00m,
                    StartAvailability = new DateTime(2025, 1, 10),
                    EndAvailability = new DateTime(2025, 12, 20),
                    SemesterAvailability = null,
                    Bedrooms = 1,
                    Bathrooms = 1,
                    Description = "Private room in shared house, includes utilities and Wi-Fi.",
                    WaterIncludedInRent = true,
                    GasIncludedInRent = true,
                    InternetIncludedInRent = true,
                    TrashIncludedInRent = true,
                    ElectricIncludedInRent = true,
                    AverageUtilitiesCost = 0m,
                    SharedRoom = false,
                    SharedRoommates = 3,
                    Furnished = true,
                    AnimalsAllowed = 0,
                    WasherDryer = 1,
                    Parking = 1,
                    DistanceFromCampus = 0.8m,
                    Photos = null,
                    PhotoData = null,
                    RoommateNumber = 3,
                    PreferredGender = Gender.Male,
                    ContactMethod = "Email",
                    Contact = "chris.taylor@example.com",
                    ContactName = "Chris Taylor",
                    Deleted = false,
                    OwnerId = 1
                }
            }
        };

        public  List<Listing> SampleListings =>  new List<Listing>
            {
                new Listing
                {
                    ListingId = 1,
                    ListingType = ListingType.Apartment,
                    Address = "123 Main St",
                    AddressLine2 = "Apt 2B",
                    City = "Cincinnati",
                    State = "OH",
                    ZipCode = "45219",
                    Country = "USA",
                    Rent = 950.00m,
                    StartAvailability = new DateTime(2025, 1, 1),
                    EndAvailability = new DateTime(2025, 8, 15),
                    SemesterAvailability = "Spring 2025",
                    Bedrooms = 2,
                    Bathrooms = 1,
                    Description = "Spacious 2-bedroom apartment near UC campus with modern kitchen and parking.",
                    WaterIncludedInRent = true,
                    GasIncludedInRent = false,
                    InternetIncludedInRent = true,
                    TrashIncludedInRent = true,
                    ElectricIncludedInRent = false,
                    AverageUtilitiesCost = 75.00m,
                    SharedRoom = false,
                    SharedRoommates = 0,
                    Furnished = true,
                    AnimalsAllowed = 1,
                    WasherDryer = 1,
                    Parking = 1,
                    DistanceFromCampus = 0.5m,
                    Photos = null,
                    PhotoData = null,
                    RoommateNumber = 0,
                    PreferredGender = Gender.Male,
                    ContactMethod = "Email",
                    Contact = "chris.taylor@example.com",
                    ContactName = "Chris Taylor",
                    Deleted = false,
                    OwnerId = 1
                },
                new Listing
                {
                    ListingId = 2,
                    ListingType = ListingType.House,
                    Address = "456 Oak Ave",
                    AddressLine2 = "",
                    City = "Cincinnati",
                    State = "OH",
                    ZipCode = "45220",
                    Country = "USA",
                    Rent = 1200.00m,
                    StartAvailability = new DateTime(2025, 5, 15),
                    EndAvailability = new DateTime(2026, 5, 15),
                    SemesterAvailability = "Summer 2025",
                    Bedrooms = 3,
                    Bathrooms = 2,
                    Description = "Cozy 3-bedroom house with fenced yard and nearby bus stop.",
                    WaterIncludedInRent = false,
                    GasIncludedInRent = false,
                    InternetIncludedInRent = true,
                    TrashIncludedInRent = true,
                    ElectricIncludedInRent = false,
                    AverageUtilitiesCost = 150.00m,
                    SharedRoom = false,
                    SharedRoommates = 0,
                    Furnished = false,
                    AnimalsAllowed = 2,
                    WasherDryer = 1,
                    Parking = 2,
                    DistanceFromCampus = 1.2m,
                    Photos = null,
                    PhotoData = null,
                    RoommateNumber = 0,
                    PreferredGender = Gender.Female,
                    ContactMethod = "Phone",
                    Contact = "513-555-1234",
                    ContactName = "Chris Taylor",
                    Deleted = false,
                    OwnerId = 1
                },
                new Listing
                {
                    ListingId = 3,
                    ListingType = ListingType.House,
                    Address = "789 Maple Blvd",
                    AddressLine2 = "Room 3",
                    City = "Cincinnati",
                    State = "OH",
                    ZipCode = "45219",
                    Country = "USA",
                    Rent = 600.00m,
                    StartAvailability = new DateTime(2025, 1, 10),
                    EndAvailability = new DateTime(2025, 12, 20),
                    SemesterAvailability = "Full Year",
                    Bedrooms = 1,
                    Bathrooms = 1,
                    Description = "Private room in shared house, includes utilities and Wi-Fi.",
                    WaterIncludedInRent = true,
                    GasIncludedInRent = true,
                    InternetIncludedInRent = true,
                    TrashIncludedInRent = true,
                    ElectricIncludedInRent = true,
                    AverageUtilitiesCost = 0m,
                    SharedRoom = false,
                    SharedRoommates = 3,
                    Furnished = true,
                    AnimalsAllowed = 0,
                    WasherDryer = 1,
                    Parking = 1,
                    DistanceFromCampus = 0.8m,
                    Photos = null,
                    PhotoData = null,
                    RoommateNumber = 3,
                    PreferredGender = Gender.Male,
                    ContactMethod = "Email",
                    Contact = "chris.taylor@example.com",
                    ContactName = "Chris Taylor",
                    Deleted = false,
                    OwnerId = 1
                }
            };
    }
}
